asar.exe "256PipeAndRolloverFixes.asm" "FluxBase2.smc"
asar.exe "AllowTilePriorityinLevelModes.asm" "FluxBase2.smc"
asar.exe "AlwaysFlowerBlock.asm" "FluxBase2.smc"
asar.exe "AlwaysYoshiQuestionBlock-No1Up.asm" "FluxBase2.smc"
asar.exe "BabyAndAdultYoshiGFXFix-ifnocape.asm" "FluxBase2.smc"
asar.exe "BabyYoshiDoesntIdleHop.asm" "FluxBase2.smc"
asar.exe "BabyYoshiGrowFreezeTimer.asm" "FluxBase2.smc"
asar.exe "BallChainYoshiInteractionFix.asm" "FluxBase2.smc"
asar.exe "BerryVerticalAndLayer2Fix.asm" "FluxBase2.smc"
asar.exe "BetterDoorEntry.asm" "FluxBase2.smc"
asar.exe "BlockSnakeTriggerFix.asm" "FluxBase2.smc"
asar.exe "Blockduplicationfix(freeram).asm" "FluxBase2.smc"
asar.exe "BobOmbSpinjumpInteraction.asm" "FluxBase2.smc"
asar.exe "BobombPaletteFixAfterKicked.asm" "FluxBase2.smc"
asar.exe "BooBatCeilingHitboxFix.asm" "FluxBase2.smc"
asar.exe "BooCeilingSpriteSlotFix.asm" "FluxBase2.smc"
asar.exe "BounceSpritePalettePerLevelRemap.asm" "FluxBase2.smc"
asar.exe "BowserFireballNoVerticalDespawn.asm" "FluxBase2.smc"
asar.exe "CapeGroundPoundSetFlag.asm" "FluxBase2.smc"
asar.exe "CapespinHitboxConsistencyV2.asm" "FluxBase2.smc"
asar.exe "CapeSpinDisable.asm" "FluxBase2.smc"
asar.exe "CeilingCheckForFlameNinjiStatueEtc.asm" "FluxBase2.smc"
asar.exe "ChuckArmPaletteFixWhenCharging.asm" "FluxBase2.smc"
asar.exe "CoinBlocksInSwitchPalaces-Disable3BlockBonusGame.asm" "FluxBase2.smc"
asar.exe "ColorDataNMIOptimizer.asm" "FluxBase2.smc"
asar.exe "ConditionalStatusBarCounterFunctions.asm" "FluxBase2.smc"
asar.exe "CourseClearModifiedMinimal.asm" "FluxBase2.smc"
asar.exe "CourseClearSkipfadeout_ramcontrolled.asm" "FluxBase2.smc"
asar.exe "CustBounceSpritesPATCH.asm" "FluxBase2.smc"
asar.exe "DeathAndDamageDisableFlag.asm" "FluxBase2.smc"
asar.exe "DigginChuckGFXFix.asm" "FluxBase2.smc"
asar.exe "DisableFirstFrameJumpAfterLandingIfFreeRAM.asm" "FluxBase2.smc"
asar.exe "DinoRhinoWallJumpFix.asm" "FluxBase2.smc"
asar.exe "DinoTorchPuffOfSmokeWhenKilled.asm" "FluxBase2.smc"
asar.exe "DolphinsEdibleByYoshi.asm" "FluxBase2.smc"
asar.exe "Dolphintailscreengfxfix.asm" "FluxBase2.smc"
asar.exe "DryBonesEtcStarInvincFix.asm" "FluxBase2.smc"
asar.exe "DryBonesMolesHammersExtraBit.asm" "FluxBase2.smc"
asar.exe "DuckDisableConditional.asm" "FluxBase2.smc"
asar.exe "ExitFromHorzPipeSoundFix.asm" "FluxBase2.smc"
asar.exe "FeatherAutoscrollFix.asm" "FluxBase2.smc"
asar.exe "FireballAmountOnScreenRAMControlled.asm" "FluxBase2.smc"
asar.exe "FireballConveyorGFXFix.asm" "FluxBase2.smc"
asar.exe "FireballCounterPatch.asm" "FluxBase2.smc"
asar.exe "FireballFlagStuff.asm" "FluxBase2.smc"
asar.exe "FireballShootUpOrDownConditional.asm" "FluxBase2.smc"
asar.exe "FireballWhenSmallAndOtherChecks.asm" "FluxBase2.smc"
asar.exe "Fireberryfix.asm" "FluxBase2.smc"
asar.exe "FishboneInitialMovementRNGFix.asm" "FluxBase2.smc"
asar.exe "FlightSpinDirectionFixKatunVersion(freeram).asm" "FluxBase2.smc"
asar.exe "FrameRules.asm" "FluxBase2.smc"
asar.exe "GarbledGFXSwimSameFrameDamage.asm" "FluxBase2.smc"
asar.exe "GoalPeaceSignPoseOnYoshiFix.asm" "FluxBase2.smc"
asar.exe "GoalSphereBehaviors.asm" "FluxBase2.smc"
asar.exe "Greyfallingplatfix.asm" "FluxBase2.smc"
asar.exe "HDMADoesntDisappearAtFileSelect.asm" "FluxBase2.smc"
asar.exe "HDMAandSpritePriorityFixes.asm" "FluxBase2.smc"
asar.exe "HorizontalCameraScrollSnapFix.asm" "FluxBase2.smc"
asar.exe "HurtAfterGoalConditional.asm" "FluxBase2.smc"
asar.exe "Instant1UpsWithoutQueue.asm" "FluxBase2.smc"
asar.exe "InvisBlockTriggeredByDeathFix.asm" "FluxBase2.smc"
asar.exe "item_box_gfx_fix.asm" "FluxBase2.smc"
asar.exe "ItemBoxButtonDisableConditional.asm" "FluxBase2.smc"
asar.exe "ItemBoxSpriteStatus.asm" "FluxBase2.smc"
asar.exe "ItemReserveFallIfDamageConditional.asm" "FluxBase2.smc"
asar.exe "ItemThrowDirection.asm" "FluxBase2.smc"
asar.exe "Koopa_eyes_offscreen_fix.asm" "FluxBase2.smc"
asar.exe "LRScrollingConditional.asm" "FluxBase2.smc"
asar.exe "LakituDeathTileFreeup.asm" "FluxBase2.smc"
asar.exe "LakituThrowSFX.asm" "FluxBase2.smc"
asar.exe "Lakitu_cloud_timer_with_extra_bit.asm" "FluxBase2.smc"
asar.exe "Layer2Fixes-TriangleAndFalloff(FreeRAM).asm" "FluxBase2.smc"
asar.exe "Layer3SmasherOffGeneratorFix.asm" "FluxBase2.smc"
asar.exe "LineGuidedSpriteSpawnLocationFix.asm" "FluxBase2.smc
asar.exe "LineGuidesGlobalAndOnOff.asm" "FluxBase2.smc"
asar.exe "LuigiDoesntNeedControllerPort2.asm" "FluxBase2.smc"
asar.exe "MagikoopaDoentRespawnIfSet.asm" "FluxBase2.smc"
asar.exe "MagikoopaPaletteFix.asm" "FluxBase2.smc"
asar.exe "MagikoopaWandVerticalFix.asm" "FluxBase2.smc"
asar.exe "MarioFireballCustomBlockLayer2InteractionFix.asm" "FluxBase2.smc"
asar.exe "MarioFireballYPosition.asm" "FluxBase2.smc"
asar.exe "MarioMovesLeftAfterGoalTapeIfFreeRAMSet.asm" "FluxBase2.smc"
asar.exe "MarioStartPerLevelTable.asm" "FluxBase2.smc"
asar.exe "MarioTileDMAMergedPaletteChange.asm" "FluxBase2.smc"
asar.exe "MegaMoleUpwardClippingFix.asm" "FluxBase2.smc"
asar.exe "MessageBoxDoesntEraseSpriteTiles.asm" "FluxBase2.smc"
asar.exe "MovingGhostHoleHitboxFix.asm" "FluxBase2.smc"
asar.exe "NetTileGFXRemap.asm" "FluxBase2.smc"
asar.exe "Net_screen_boundary_fix.asm" "FluxBase2.smc"
asar.exe "NoBonusGameOn100Stars.asm" "FluxBase2.smc"
asar.exe "NoCapeFloatDelayOnRelease.asm" "FluxBase2.smc"
asar.exe "NoCarryIf.asm" "FluxBase2.smc"
asar.exe "NoMoreFootballRNG.asm" "FluxBase2.smc"
asar.exe "NoMoreSpriteTileLimits.asm" "FluxBase2.smc"
asar.exe "NoPodobooTimerRNG.asm" "FluxBase2.smc"
asar.exe "NoSilentBulletBill.asm" "FluxBase2.smc"
asar.exe "NoteblockAndWallClipFix.asm" "FluxBase2.smc"
asar.exe "NoteBlockFixesAndFeatures.asm" "FluxBase2.smc"
asar.exe "NoYoshiRescueMessage.asm" "FluxBase2.smc"
asar.exe "Optimize1F0.asm" "FluxBase2.smc"
asar.exe "optimize_status_bar_nmi.asm" "FluxBase2.smc"
asar.exe "PauseBufferLengthToggle.asm" "FluxBase2.smc"
asar.exe "PauseFixes.asm" "FluxBase2.smc"
asar.exe "Pballooncloudclipping.asm" "FluxBase2.smc"
asar.exe "PerLevelPSwitchBulletShooterAndPBalloonTimers(Patch).asm" "FluxBase2.smc"
asar.exe "PipeHitboxWiden.asm" "FluxBase2.smc"
asar.exe "PiranhaRemap.asm" "FluxBase2.smc"
asar.exe "PiranhaStemPaletteFix.asm" "FluxBase2.smc"
asar.exe "PitchinChuckNoTurnExtraBit.asm" "FluxBase2.smc"
asar.exe "PlaceableAutokickedshells.asm" "FluxBase2.smc"
asar.exe "PlaceableThrowBlock-sprite53.asm" "FluxBase2.smc"
asar.exe "Placeablediscoshell-spriteDD.asm" "FluxBase2.smc"
asar.exe "PlaylistPatch(FreeRAM).asm" "FluxBase2.smc" 
asar.exe "PodobooBuoyancyFix.asm" "FluxBase2.smc"
asar.exe "PodobooYoshiDamageInteraction.asm" "FluxBase2.smc"
asar.exe "PodobooYoshiGFXFix.asm" "FluxBase2.smc"
asar.exe "PokeySegmentFixes.asm" "FluxBase2.smc"
asar.exe "PreventItemDropWhenPowerup.asm" "FluxBase2.smc"
asar.exe "ProperFreezeYoshiDuringKeyholeSequence.asm" "FluxBase2.smc"
asar.exe "QuestionBlockSpawnedItemCollisionFix.asm" "FluxBase2.smc"
asar.exe "RemapBounceSpritesAndOthers.asm" "FluxBase2.smc"
asar.exe "RemapRipVanZZZ.asm" "FluxBase2.smc"
asar.exe "RemapSpriteBlocksPalettes(FlyingEatingEtc).asm" "FluxBase2.smc"
asar.exe "RemoveYoshiIdleBouncing.asm" "FluxBase2.smc"
asar.exe "ReznorBossBridgeFix.asm" "FluxBase2.smc"
asar.exe "ReznorBridgeWhenUsedInOtherLevelsFix.asm" "FluxBase2.smc"
asar.exe "RopeGlitchFix.asm" "FluxBase2.smc"
asar.exe "ScreenScrollingPipesMinimalFunction.asm" "FluxBase2.smc"
asar.exe "SideExitTeleportIfSet.asm" "FluxBase2.smc"
asar.exe "SilentOWFix.asm" "FluxBase2.smc"
asar.exe "Slide_kill_gfx_fix.asm" "FluxBase2.smc"
asar.exe "SkipPlayerSelect.asm" "FluxBase2.smc"
asar.exe "SlowHorizontalLayer2BGScroll.asm" "FluxBase2.smc"
asar.exe "SpawnCarryableStateSpritesExBit.asm" "FluxBase2.smc"
asar.exe "SpeedOscillationConditional.asm" "FluxBase2.smc"
asar.exe "SpinJumpOnTwoSpritesAtOnceFix.asm" "FluxBase2.smc"
asar.exe "SpotlightDarkBGFix.asm" "FluxBase2.smc"
asar.exe "SpotlightOptimize.asm" "FluxBase2.smc"
asar.exe "SpringGrabFix.asm" "FluxBase2.smc"
asar.exe "Sprite_item_box.asm" "FluxBase2.smc"
asar.exe "SpriteContactGFXCutoffFix.asm" "FluxBase2.smc"
asar.exe "SpriteSlotAndDuplicateSpriteFixes.asm" "FluxBase2.smc"
asar.exe "Spriteheightfix.asm" "FluxBase2.smc"
asar.exe "SpritesDontDisappearAtFileSelect.asm" "FluxBase2.smc"
asar.exe "SpritesEdgeScreenInteractionFix.asm" "FluxBase2.smc"
asar.exe "StarTimeLowSFX.asm" "FluxBase2.smc"
asar.exe "StatusBarConditional.asm" "FluxBase2.smc"
asar.exe "SumoLightningByItselfMainSFX.asm" "FluxBase2.smc"
asar.exe "SunkenGhostShipGlitch.asm" "FluxBase2.smc"
asar.exe "SwapYoshiFireballWithFlopCheepGlobal.asm" "FluxBase2.smc"
asar.exe "SwitchPalaceYumpCheck.asm" "FluxBase2.smc"
asar.exe "SwooperGeneratorGFXFix.asm" "FluxBase2.smc"
asar.exe "ThrowblockSplashGFXFix.asm" "FluxBase2.smc"
asar.exe "ThwompFallingBehaviorFix.asm" "FluxBase2.smc"
asar.exe "Tide-FloatPlatAndDolphinFix.asm" "FluxBase2.smc"
asar.exe "TideCurrentAndRegularWaterCoexist.asm" "FluxBase2.smc"
asar.exe "Timeupfix.asm" "FluxBase2.smc"
asar.exe "TitleScreenAndOW.asm" "FluxBase2.smc"
asar.exe "TitleScreenWhiteTileFix.asm" "FluxBase2.smc"
asar.exe "TurnblockBridgeGFXRemapAndFix.asm" "FluxBase2.smc"
asar.exe "UpthrowSpriteToCeilingBlocksBugFix.asm" "FluxBase2.smc"
asar.exe "VanillaPSwitchYoshiDup.asm" "FluxBase2.smc"
asar.exe "VerticalScreenWrapAllow.asm" "FluxBase2.smc"
asar.exe "VineGrowSpeedPatch.asm" "FluxBase2.smc"
asar.exe "VolcanoLotusKilledByMarioFireball.asm" "FluxBase2.smc"
asar.exe "VRAMOptimization.asm" "FluxBase2.smc"
asar.exe "WallSlideAndKickFreeRAMConditional.asm" "FluxBase2.smc"
asar.exe "WaterSplashGFXPositionFix.asm" "FluxBase2.smc"
asar.exe "WelcomeMessageDisplayTime.asm" "FluxBase2.smc"
asar.exe "WigglerFlowerSpawnFix.asm" "FluxBase2.smc"
asar.exe "YellowJumpingKoopaFrameRule.asm" "FluxBase2.smc"
asar.exe "Yoshi-LineGuidedEnemyImmunityFix.asm" "FluxBase2.smc"
asar.exe "YoshiCoinFixes.asm" "FluxBase2.smc"
asar.exe "YoshiDismountBlockPatch.asm" "FluxBase2.smc"
asar.exe "YoshiFaceRightOnExtraBit.asm" "FluxBase2.smc"
asar.exe "YoshiGroundPoundScreenWrapGlitch.asm" "FluxBase2.smc"
asar.exe "YoshiHurtByExtendedSpriteSpeedFix.asm" "FluxBase2.smc"
asar.exe "YoshiIdleGFXDisplacementFix.asm" "FluxBase2.smc"
asar.exe "YoshiSmallFireballSpitPositionAdjust.asm" "FluxBase2.smc"
asar.exe "YoshiSpriteInteractionsFix-Revised.asm" "FluxBase2.smc"
asar.exe "YoshiTongueCutoffFix.asm" "FluxBase2.smc"
asar.exe "YoshiPipeAnimationFix.asm" "FluxBase2.smc"

asar.exe "InteractionLine/InteractionLinePatch.asm" "FluxBase2.smc"
asar.exe "YoshiBlockEat/EdibleBlocksPatch.asm" "FluxBase2.smc"
asar.exe "YoshiFireballCustomInteract/yoshi_fireballPatch.asm" "FluxBase2.smc"

PAUSE

:: asar.exe "optimize_block_changeFixed.asm" "FluxBase2.smc"

:: There should be ~184 total patches: 179 patches [+1 SSPDefines] in main folder, + 3 in subfolders
:: Some patches are installed with Ubers or sprites, like POOT (portable orb thing)

:: You need to run PIXI before "PlaceableAutokickedshells.asm"
:: You need to run PIXI before  "Lakitu_cloud_timer_with_extra_bit.asm"

:: Previously had VRAM opt vefore MarioTileDMA, but...

:: Save for last, RECOMMENDED or UNCERTAIN:

:: asar.exe "Layer3MessageBoxPatch.asm" "FluxBase2.smc" (before VRAM and DMA?)
:: asar.exe "Recommended/CapespinLayer2WarpFix.asm" "FluxBase2.smc"
:: asar.exe "Recommended/ScreenScrollingPipesSpriteFixes.asm" "FluxBase2.smc" 
:: asar.exe "Recommended/SmokeOffscreenGlobalFixEtc.asm" "FluxBase2.smc"
:: asar.exe "(ReadBeforeApplying)SpritePropertiesExtraBit.asm" "FluxBase2.smc"


:: INCOMPATIBLE/BROKEN or REMOVED:
:: asar.exe "FreeUpSpriteTiles69and83.asm" "FluxBase2.smc"
:: asar.exe "Layer3TideControlAndFixes.asm" "FluxBase2.smc"
:: asar.exe "ScoreSpritesConditional.asm" "FluxBase2.smc"
:: asar.exe "UpsideDownSlopesActAsTilesetFix.asm" "FluxBase2.smc"
:: asar.exe "NoPressedVanillaPSwitchCarry.asm" "FluxBase2.smc" (incompt with NoCarryIf) 
:: VineMarioClimbingSpeedPatch.asm